[package]
name = "pydantic-stream-python"
version = "0.3.0"
edition = "2024"

[lib]
name = "_native"
crate-type = ["cdylib", "rlib"]

[dependencies]
pydantic-stream-core = { path = "../pydantic-stream-core" }
pyo3 = "0.28"

[features]
extension-module = ["pyo3/extension-module"]

[lints]
workspace = true
