"""Type stubs for the Rust _native extension module."""

from __future__ import annotations

class FieldSpec:
    def __init__(self, output_key: str, nested: ObjectSpec | None = None) -> None: ...
    @property
    def output_key(self) -> str: ...
    def __repr__(self) -> str: ...

class ObjectSpec:
    def __init__(self, fields_by_input_key: dict[str, FieldSpec]) -> None: ...
    def __repr__(self) -> str: ...
    def __len__(self) -> int: ...
    def __contains__(self, key: str) -> bool: ...

class StreamingProjectionError(RuntimeError): ...

# Streaming (no projection)
def extract_array_items(
    data: bytes,
    is_start: bool = True,
) -> tuple[list[bytes], int, bool]: ...

# Projection (requires spec)
def project_array(data: bytes, spec: ObjectSpec) -> bytes: ...
def project_array_items(data: bytes, spec: ObjectSpec) -> list[bytes]: ...
def project_object(data: bytes, spec: ObjectSpec) -> bytes: ...
def project_jsonl(data: bytes, spec: ObjectSpec) -> list[bytes]: ...
def project_array_items_sliced(
    data: bytes,
    spec: ObjectSpec,
    prefix: str | None = None,
    start: int = 0,
    stop: int | None = None,
    step: int = 1,
) -> list[bytes]: ...
def project_array_nav(
    data: bytes,
    spec: ObjectSpec,
    prefix: str | None = None,
) -> bytes: ...
def project_array_items_partial(
    data: bytes,
    spec: ObjectSpec,
    is_start: bool = True,
) -> tuple[list[bytes], int, bool]: ...
